create table Channel (id bigint generated by default as identity, custom boolean not null, type varchar(255), value varchar(255), primary key (id))
create table Contact (id bigint generated by default as identity, active boolean not null, addressLine1 varchar(255), addressLine2 varchar(255), country varchar(255), postcode varchar(255), state varchar(255), suburb varchar(255), alternateKey varchar(255), companyTitle varchar(255), custom boolean not null, firstName varchar(255), lastName varchar(255), image_id bigint, location_id bigint, primary key (id))
create table Contact_Channel (ContactEntity_id bigint not null, channels_id bigint not null)
create table Image (id bigint generated by default as identity, active boolean not null, bytes varchar(255) for bit data, custom boolean not null, desc varchar(255), dimension varchar(255) for bit data, mimeType varchar(255), primary key (id))
create table Location (id bigint generated by default as identity, active boolean not null, addressLine1 varchar(255), addressLine2 varchar(255), country varchar(255), postcode varchar(255), state varchar(255), suburb varchar(255), alternateKey varchar(255), custom boolean not null, desc varchar(255), primary key (id))
create table Location_Location (LocationEntity_id bigint not null, subLocations_id bigint not null)
create table OrgUnit (id bigint generated by default as identity, active boolean not null, alternateKey varchar(255), custom boolean not null, desc varchar(255), type_id bigint, primary key (id))
create table OrgUnit_Contact (OrgUnitEntity_id bigint not null, contacts_id bigint not null)
create table OrgUnit_OrgUnit (OrgUnitEntity_id bigint not null, subOrgUnits_id bigint not null)
create table OrgUnit_Position (OrgUnitEntity_id bigint not null, positions_id bigint not null)
create table OrgUnitType (id bigint generated by default as identity, alternateKey varchar(255), custom boolean not null, desc varchar(255), primary key (id))
create table Position (id bigint generated by default as identity, active boolean not null, alternateKey varchar(255), custom boolean not null, desc varchar(255), primary key (id))
create table Position_Contact (PositionEntity_id bigint not null, contacts_id bigint not null)
create table Position_Position (PositionEntity_id bigint not null, subPositions_id bigint not null)
alter table Contact_Channel add constraint UK_iwdhuay53ltyst9wx8cx6i0mf unique (channels_id)
alter table Location_Location add constraint UK_rf4ieuag13blatyfbb7je34ow unique (subLocations_id)
alter table OrgUnit_Contact add constraint UK_tq0xifqlsqh56gnej5xfvdthk unique (contacts_id)
alter table OrgUnit_OrgUnit add constraint UK_hl4o6ip8dtwa8ufnaxq3aa8pc unique (subOrgUnits_id)
alter table OrgUnit_Position add constraint UK_qugyq06u8k4hpxfeapg7eieqt unique (positions_id)
alter table Position_Contact add constraint UK_hthrdh94j8udsr5dnlyskw7er unique (contacts_id)
alter table Position_Position add constraint UK_e7uf9be61m5jjytjeuoo2d1k9 unique (subPositions_id)
alter table Contact add constraint FKha6v2q0p3tilc9iiru7qou3vl foreign key (image_id) references Image
alter table Contact add constraint FKfphjtq0vofgr4dqi5um38wnkn foreign key (location_id) references Location
alter table Contact_Channel add constraint FKco9j5y5frhg866vsxygpbjnn8 foreign key (channels_id) references Channel
alter table Contact_Channel add constraint FKf2y729ik4qnfq1rn58h582y02 foreign key (ContactEntity_id) references Contact
alter table Location_Location add constraint FK9wqyt752xxb1tr5v6plosgpa5 foreign key (subLocations_id) references Location
alter table Location_Location add constraint FKf95km4wtrtpb90m999jl6pttb foreign key (LocationEntity_id) references Location
alter table OrgUnit add constraint FK5kmcpm94y4gx2oas5ixrn0sji foreign key (type_id) references OrgUnitType
alter table OrgUnit_Contact add constraint FKqwerylm61ji990c4ce829ixt4 foreign key (contacts_id) references Contact
alter table OrgUnit_Contact add constraint FKrluqhj0yqc8nkb5e8a7vxcjaa foreign key (OrgUnitEntity_id) references OrgUnit
alter table OrgUnit_OrgUnit add constraint FKenpdvjkbg8ax8kjgpadbbthqy foreign key (subOrgUnits_id) references OrgUnit
alter table OrgUnit_OrgUnit add constraint FKegyydydt6ewpmt1d195yegbhe foreign key (OrgUnitEntity_id) references OrgUnit
alter table OrgUnit_Position add constraint FKdnwt1fpxnrkush8wiqvurf68g foreign key (positions_id) references Position
alter table OrgUnit_Position add constraint FKjvok92mrukpvehk3jin3jtuas foreign key (OrgUnitEntity_id) references OrgUnit
alter table Position_Contact add constraint FKiit793ur4r60mo1ipdsjokdlu foreign key (contacts_id) references Contact
alter table Position_Contact add constraint FKeqx8cqg3gsbp95xeebuxs67mk foreign key (PositionEntity_id) references Position
alter table Position_Position add constraint FK4xeovl3w59i87ovnt0krb1xss foreign key (subPositions_id) references Position
alter table Position_Position add constraint FK364ebxj7nj74k4efxtr994681 foreign key (PositionEntity_id) references Position
create table Channel (id bigint generated by default as identity, custom boolean not null, type varchar(255), value varchar(255), primary key (id))
create table Contact (id bigint generated by default as identity, active boolean not null, addressLine1 varchar(255), addressLine2 varchar(255), country varchar(255), postcode varchar(255), state varchar(255), suburb varchar(255), alternateKey varchar(255), companyTitle varchar(255), custom boolean not null, firstName varchar(255), lastName varchar(255), image_id bigint, location_id bigint, primary key (id))
create table Contact_Channel (ContactEntity_id bigint not null, channels_id bigint not null)
create table Image (id bigint generated by default as identity, active boolean not null, bytes varchar(255) for bit data, custom boolean not null, desc varchar(255), dimension varchar(255) for bit data, mimeType varchar(255), primary key (id))
create table Location (id bigint generated by default as identity, active boolean not null, addressLine1 varchar(255), addressLine2 varchar(255), country varchar(255), postcode varchar(255), state varchar(255), suburb varchar(255), alternateKey varchar(255), custom boolean not null, desc varchar(255), primary key (id))
create table Location_Location (LocationEntity_id bigint not null, subLocations_id bigint not null)
create table OrgUnit (id bigint generated by default as identity, active boolean not null, alternateKey varchar(255), custom boolean not null, desc varchar(255), type_id bigint, primary key (id))
create table OrgUnit_Contact (OrgUnitEntity_id bigint not null, contacts_id bigint not null)
create table OrgUnit_OrgUnit (OrgUnitEntity_id bigint not null, subOrgUnits_id bigint not null)
create table OrgUnit_Position (OrgUnitEntity_id bigint not null, positions_id bigint not null)
create table OrgUnitType (id bigint generated by default as identity, alternateKey varchar(255), custom boolean not null, desc varchar(255), primary key (id))
create table Position (id bigint generated by default as identity, active boolean not null, alternateKey varchar(255), custom boolean not null, desc varchar(255), primary key (id))
create table Position_Contact (PositionEntity_id bigint not null, contacts_id bigint not null)
create table Position_Position (PositionEntity_id bigint not null, subPositions_id bigint not null)
alter table Contact_Channel add constraint UK_iwdhuay53ltyst9wx8cx6i0mf unique (channels_id)
alter table Location_Location add constraint UK_rf4ieuag13blatyfbb7je34ow unique (subLocations_id)
alter table OrgUnit_Contact add constraint UK_tq0xifqlsqh56gnej5xfvdthk unique (contacts_id)
alter table OrgUnit_OrgUnit add constraint UK_hl4o6ip8dtwa8ufnaxq3aa8pc unique (subOrgUnits_id)
alter table OrgUnit_Position add constraint UK_qugyq06u8k4hpxfeapg7eieqt unique (positions_id)
alter table Position_Contact add constraint UK_hthrdh94j8udsr5dnlyskw7er unique (contacts_id)
alter table Position_Position add constraint UK_e7uf9be61m5jjytjeuoo2d1k9 unique (subPositions_id)
alter table Contact add constraint FKha6v2q0p3tilc9iiru7qou3vl foreign key (image_id) references Image
alter table Contact add constraint FKfphjtq0vofgr4dqi5um38wnkn foreign key (location_id) references Location
alter table Contact_Channel add constraint FKco9j5y5frhg866vsxygpbjnn8 foreign key (channels_id) references Channel
alter table Contact_Channel add constraint FKf2y729ik4qnfq1rn58h582y02 foreign key (ContactEntity_id) references Contact
alter table Location_Location add constraint FK9wqyt752xxb1tr5v6plosgpa5 foreign key (subLocations_id) references Location
alter table Location_Location add constraint FKf95km4wtrtpb90m999jl6pttb foreign key (LocationEntity_id) references Location
alter table OrgUnit add constraint FK5kmcpm94y4gx2oas5ixrn0sji foreign key (type_id) references OrgUnitType
alter table OrgUnit_Contact add constraint FKqwerylm61ji990c4ce829ixt4 foreign key (contacts_id) references Contact
alter table OrgUnit_Contact add constraint FKrluqhj0yqc8nkb5e8a7vxcjaa foreign key (OrgUnitEntity_id) references OrgUnit
alter table OrgUnit_OrgUnit add constraint FKenpdvjkbg8ax8kjgpadbbthqy foreign key (subOrgUnits_id) references OrgUnit
alter table OrgUnit_OrgUnit add constraint FKegyydydt6ewpmt1d195yegbhe foreign key (OrgUnitEntity_id) references OrgUnit
alter table OrgUnit_Position add constraint FKdnwt1fpxnrkush8wiqvurf68g foreign key (positions_id) references Position
alter table OrgUnit_Position add constraint FKjvok92mrukpvehk3jin3jtuas foreign key (OrgUnitEntity_id) references OrgUnit
alter table Position_Contact add constraint FKiit793ur4r60mo1ipdsjokdlu foreign key (contacts_id) references Contact
alter table Position_Contact add constraint FKeqx8cqg3gsbp95xeebuxs67mk foreign key (PositionEntity_id) references Position
alter table Position_Position add constraint FK4xeovl3w59i87ovnt0krb1xss foreign key (subPositions_id) references Position
alter table Position_Position add constraint FK364ebxj7nj74k4efxtr994681 foreign key (PositionEntity_id) references Position
create table Channel (id bigint generated by default as identity, custom boolean not null, type varchar(255), value varchar(255), primary key (id))
create table Contact (id bigint generated by default as identity, active boolean not null, addressLine1 varchar(255), addressLine2 varchar(255), country varchar(255), postcode varchar(255), state varchar(255), suburb varchar(255), alternateKey varchar(255), companyTitle varchar(255), custom boolean not null, firstName varchar(255), lastName varchar(255), image_id bigint, location_id bigint, primary key (id))
create table Contact_Channel (ContactEntity_id bigint not null, channels_id bigint not null)
create table Image (id bigint generated by default as identity, active boolean not null, bytes varchar(255) for bit data, custom boolean not null, desc varchar(255), dimension varchar(255) for bit data, mimeType varchar(255), primary key (id))
create table Location (id bigint generated by default as identity, active boolean not null, addressLine1 varchar(255), addressLine2 varchar(255), country varchar(255), postcode varchar(255), state varchar(255), suburb varchar(255), alternateKey varchar(255), custom boolean not null, desc varchar(255), primary key (id))
create table Location_Location (LocationEntity_id bigint not null, subLocations_id bigint not null)
create table OrgUnit (id bigint generated by default as identity, active boolean not null, alternateKey varchar(255), custom boolean not null, desc varchar(255), type_id bigint, primary key (id))
create table OrgUnit_Contact (OrgUnitEntity_id bigint not null, contacts_id bigint not null)
create table OrgUnit_OrgUnit (OrgUnitEntity_id bigint not null, subOrgUnits_id bigint not null)
create table OrgUnit_Position (OrgUnitEntity_id bigint not null, positions_id bigint not null)
create table OrgUnitType (id bigint generated by default as identity, alternateKey varchar(255), custom boolean not null, desc varchar(255), primary key (id))
create table Position (id bigint generated by default as identity, active boolean not null, alternateKey varchar(255), custom boolean not null, desc varchar(255), primary key (id))
create table Position_Contact (PositionEntity_id bigint not null, contacts_id bigint not null)
create table Position_Position (PositionEntity_id bigint not null, subPositions_id bigint not null)
alter table Contact_Channel add constraint UK_iwdhuay53ltyst9wx8cx6i0mf unique (channels_id)
alter table Location_Location add constraint UK_rf4ieuag13blatyfbb7je34ow unique (subLocations_id)
alter table OrgUnit_Contact add constraint UK_tq0xifqlsqh56gnej5xfvdthk unique (contacts_id)
alter table OrgUnit_OrgUnit add constraint UK_hl4o6ip8dtwa8ufnaxq3aa8pc unique (subOrgUnits_id)
alter table OrgUnit_Position add constraint UK_qugyq06u8k4hpxfeapg7eieqt unique (positions_id)
alter table Position_Contact add constraint UK_hthrdh94j8udsr5dnlyskw7er unique (contacts_id)
alter table Position_Position add constraint UK_e7uf9be61m5jjytjeuoo2d1k9 unique (subPositions_id)
alter table Contact add constraint FKha6v2q0p3tilc9iiru7qou3vl foreign key (image_id) references Image
alter table Contact add constraint FKfphjtq0vofgr4dqi5um38wnkn foreign key (location_id) references Location
alter table Contact_Channel add constraint FKco9j5y5frhg866vsxygpbjnn8 foreign key (channels_id) references Channel
alter table Contact_Channel add constraint FKf2y729ik4qnfq1rn58h582y02 foreign key (ContactEntity_id) references Contact
alter table Location_Location add constraint FK9wqyt752xxb1tr5v6plosgpa5 foreign key (subLocations_id) references Location
alter table Location_Location add constraint FKf95km4wtrtpb90m999jl6pttb foreign key (LocationEntity_id) references Location
alter table OrgUnit add constraint FK5kmcpm94y4gx2oas5ixrn0sji foreign key (type_id) references OrgUnitType
alter table OrgUnit_Contact add constraint FKqwerylm61ji990c4ce829ixt4 foreign key (contacts_id) references Contact
alter table OrgUnit_Contact add constraint FKrluqhj0yqc8nkb5e8a7vxcjaa foreign key (OrgUnitEntity_id) references OrgUnit
alter table OrgUnit_OrgUnit add constraint FKenpdvjkbg8ax8kjgpadbbthqy foreign key (subOrgUnits_id) references OrgUnit
alter table OrgUnit_OrgUnit add constraint FKegyydydt6ewpmt1d195yegbhe foreign key (OrgUnitEntity_id) references OrgUnit
alter table OrgUnit_Position add constraint FKdnwt1fpxnrkush8wiqvurf68g foreign key (positions_id) references Position
alter table OrgUnit_Position add constraint FKjvok92mrukpvehk3jin3jtuas foreign key (OrgUnitEntity_id) references OrgUnit
alter table Position_Contact add constraint FKiit793ur4r60mo1ipdsjokdlu foreign key (contacts_id) references Contact
alter table Position_Contact add constraint FKeqx8cqg3gsbp95xeebuxs67mk foreign key (PositionEntity_id) references Position
alter table Position_Position add constraint FK4xeovl3w59i87ovnt0krb1xss foreign key (subPositions_id) references Position
alter table Position_Position add constraint FK364ebxj7nj74k4efxtr994681 foreign key (PositionEntity_id) references Position
create table Channel (id bigint generated by default as identity, custom boolean not null, type varchar(255), value varchar(255), primary key (id))
create table Contact (id bigint generated by default as identity, active boolean not null, addressLine1 varchar(255), addressLine2 varchar(255), country varchar(255), postcode varchar(255), state varchar(255), suburb varchar(255), alternateKey varchar(255), companyTitle varchar(255), custom boolean not null, firstName varchar(255), lastName varchar(255), image_id bigint, location_id bigint, primary key (id))
create table Contact_Channel (ContactEntity_id bigint not null, channels_id bigint not null)
create table Image (id bigint generated by default as identity, active boolean not null, bytes varchar(255) for bit data, custom boolean not null, desc varchar(255), dimension varchar(255) for bit data, mimeType varchar(255), primary key (id))
create table Location (id bigint generated by default as identity, active boolean not null, addressLine1 varchar(255), addressLine2 varchar(255), country varchar(255), postcode varchar(255), state varchar(255), suburb varchar(255), alternateKey varchar(255), custom boolean not null, desc varchar(255), primary key (id))
create table Location_Location (LocationEntity_id bigint not null, subLocations_id bigint not null)
create table OrgUnit (id bigint generated by default as identity, active boolean not null, alternateKey varchar(255), custom boolean not null, desc varchar(255), type_id bigint, primary key (id))
create table OrgUnit_Contact (OrgUnitEntity_id bigint not null, contacts_id bigint not null)
create table OrgUnit_OrgUnit (OrgUnitEntity_id bigint not null, subOrgUnits_id bigint not null)
create table OrgUnit_Position (OrgUnitEntity_id bigint not null, positions_id bigint not null)
create table OrgUnitType (id bigint generated by default as identity, alternateKey varchar(255), custom boolean not null, desc varchar(255), primary key (id))
create table Position (id bigint generated by default as identity, active boolean not null, alternateKey varchar(255), custom boolean not null, desc varchar(255), primary key (id))
create table Position_Contact (PositionEntity_id bigint not null, contacts_id bigint not null)
create table Position_Position (PositionEntity_id bigint not null, subPositions_id bigint not null)
alter table Contact_Channel add constraint UK_iwdhuay53ltyst9wx8cx6i0mf unique (channels_id)
alter table Location_Location add constraint UK_rf4ieuag13blatyfbb7je34ow unique (subLocations_id)
alter table OrgUnit_Contact add constraint UK_tq0xifqlsqh56gnej5xfvdthk unique (contacts_id)
alter table OrgUnit_OrgUnit add constraint UK_hl4o6ip8dtwa8ufnaxq3aa8pc unique (subOrgUnits_id)
alter table OrgUnit_Position add constraint UK_qugyq06u8k4hpxfeapg7eieqt unique (positions_id)
alter table Position_Contact add constraint UK_hthrdh94j8udsr5dnlyskw7er unique (contacts_id)
alter table Position_Position add constraint UK_e7uf9be61m5jjytjeuoo2d1k9 unique (subPositions_id)
alter table Contact add constraint FKha6v2q0p3tilc9iiru7qou3vl foreign key (image_id) references Image
alter table Contact add constraint FKfphjtq0vofgr4dqi5um38wnkn foreign key (location_id) references Location
alter table Contact_Channel add constraint FKco9j5y5frhg866vsxygpbjnn8 foreign key (channels_id) references Channel
alter table Contact_Channel add constraint FKf2y729ik4qnfq1rn58h582y02 foreign key (ContactEntity_id) references Contact
alter table Location_Location add constraint FK9wqyt752xxb1tr5v6plosgpa5 foreign key (subLocations_id) references Location
alter table Location_Location add constraint FKf95km4wtrtpb90m999jl6pttb foreign key (LocationEntity_id) references Location
alter table OrgUnit add constraint FK5kmcpm94y4gx2oas5ixrn0sji foreign key (type_id) references OrgUnitType
alter table OrgUnit_Contact add constraint FKqwerylm61ji990c4ce829ixt4 foreign key (contacts_id) references Contact
alter table OrgUnit_Contact add constraint FKrluqhj0yqc8nkb5e8a7vxcjaa foreign key (OrgUnitEntity_id) references OrgUnit
alter table OrgUnit_OrgUnit add constraint FKenpdvjkbg8ax8kjgpadbbthqy foreign key (subOrgUnits_id) references OrgUnit
alter table OrgUnit_OrgUnit add constraint FKegyydydt6ewpmt1d195yegbhe foreign key (OrgUnitEntity_id) references OrgUnit
alter table OrgUnit_Position add constraint FKdnwt1fpxnrkush8wiqvurf68g foreign key (positions_id) references Position
alter table OrgUnit_Position add constraint FKjvok92mrukpvehk3jin3jtuas foreign key (OrgUnitEntity_id) references OrgUnit
alter table Position_Contact add constraint FKiit793ur4r60mo1ipdsjokdlu foreign key (contacts_id) references Contact
alter table Position_Contact add constraint FKeqx8cqg3gsbp95xeebuxs67mk foreign key (PositionEntity_id) references Position
alter table Position_Position add constraint FK4xeovl3w59i87ovnt0krb1xss foreign key (subPositions_id) references Position
alter table Position_Position add constraint FK364ebxj7nj74k4efxtr994681 foreign key (PositionEntity_id) references Position
create table Channel (id bigint generated by default as identity, custom boolean not null, type varchar(255), value varchar(255), primary key (id))
create table Contact (id bigint generated by default as identity, active boolean not null, addressLine1 varchar(255), addressLine2 varchar(255), country varchar(255), postcode varchar(255), state varchar(255), suburb varchar(255), alternateKey varchar(255), companyTitle varchar(255), custom boolean not null, firstName varchar(255), lastName varchar(255), image_id bigint, location_id bigint, primary key (id))
create table Contact_Channel (ContactEntity_id bigint not null, channels_id bigint not null)
create table Image (id bigint generated by default as identity, active boolean not null, bytes varchar(255) for bit data, custom boolean not null, desc varchar(255), dimension varchar(255) for bit data, mimeType varchar(255), primary key (id))
create table Location (id bigint generated by default as identity, active boolean not null, addressLine1 varchar(255), addressLine2 varchar(255), country varchar(255), postcode varchar(255), state varchar(255), suburb varchar(255), alternateKey varchar(255), custom boolean not null, desc varchar(255), primary key (id))
create table Location_Location (LocationEntity_id bigint not null, subLocations_id bigint not null)
create table OrgUnit (id bigint generated by default as identity, active boolean not null, alternateKey varchar(255), custom boolean not null, desc varchar(255), type_id bigint, primary key (id))
create table OrgUnit_Contact (OrgUnitEntity_id bigint not null, contacts_id bigint not null)
create table OrgUnit_OrgUnit (OrgUnitEntity_id bigint not null, subOrgUnits_id bigint not null)
create table OrgUnit_Position (OrgUnitEntity_id bigint not null, positions_id bigint not null)
create table OrgUnitType (id bigint generated by default as identity, alternateKey varchar(255), custom boolean not null, desc varchar(255), primary key (id))
create table Position (id bigint generated by default as identity, active boolean not null, alternateKey varchar(255), custom boolean not null, desc varchar(255), primary key (id))
create table Position_Contact (PositionEntity_id bigint not null, contacts_id bigint not null)
create table Position_Position (PositionEntity_id bigint not null, subPositions_id bigint not null)
alter table Contact_Channel add constraint UK_iwdhuay53ltyst9wx8cx6i0mf unique (channels_id)
alter table Location_Location add constraint UK_rf4ieuag13blatyfbb7je34ow unique (subLocations_id)
alter table OrgUnit_Contact add constraint UK_tq0xifqlsqh56gnej5xfvdthk unique (contacts_id)
alter table OrgUnit_OrgUnit add constraint UK_hl4o6ip8dtwa8ufnaxq3aa8pc unique (subOrgUnits_id)
alter table OrgUnit_Position add constraint UK_qugyq06u8k4hpxfeapg7eieqt unique (positions_id)
alter table Position_Contact add constraint UK_hthrdh94j8udsr5dnlyskw7er unique (contacts_id)
alter table Position_Position add constraint UK_e7uf9be61m5jjytjeuoo2d1k9 unique (subPositions_id)
alter table Contact add constraint FKha6v2q0p3tilc9iiru7qou3vl foreign key (image_id) references Image
alter table Contact add constraint FKfphjtq0vofgr4dqi5um38wnkn foreign key (location_id) references Location
alter table Contact_Channel add constraint FKco9j5y5frhg866vsxygpbjnn8 foreign key (channels_id) references Channel
alter table Contact_Channel add constraint FKf2y729ik4qnfq1rn58h582y02 foreign key (ContactEntity_id) references Contact
alter table Location_Location add constraint FK9wqyt752xxb1tr5v6plosgpa5 foreign key (subLocations_id) references Location
alter table Location_Location add constraint FKf95km4wtrtpb90m999jl6pttb foreign key (LocationEntity_id) references Location
alter table OrgUnit add constraint FK5kmcpm94y4gx2oas5ixrn0sji foreign key (type_id) references OrgUnitType
alter table OrgUnit_Contact add constraint FKqwerylm61ji990c4ce829ixt4 foreign key (contacts_id) references Contact
alter table OrgUnit_Contact add constraint FKrluqhj0yqc8nkb5e8a7vxcjaa foreign key (OrgUnitEntity_id) references OrgUnit
alter table OrgUnit_OrgUnit add constraint FKenpdvjkbg8ax8kjgpadbbthqy foreign key (subOrgUnits_id) references OrgUnit
alter table OrgUnit_OrgUnit add constraint FKegyydydt6ewpmt1d195yegbhe foreign key (OrgUnitEntity_id) references OrgUnit
alter table OrgUnit_Position add constraint FKdnwt1fpxnrkush8wiqvurf68g foreign key (positions_id) references Position
alter table OrgUnit_Position add constraint FKjvok92mrukpvehk3jin3jtuas foreign key (OrgUnitEntity_id) references OrgUnit
alter table Position_Contact add constraint FKiit793ur4r60mo1ipdsjokdlu foreign key (contacts_id) references Contact
alter table Position_Contact add constraint FKeqx8cqg3gsbp95xeebuxs67mk foreign key (PositionEntity_id) references Position
alter table Position_Position add constraint FK4xeovl3w59i87ovnt0krb1xss foreign key (subPositions_id) references Position
alter table Position_Position add constraint FK364ebxj7nj74k4efxtr994681 foreign key (PositionEntity_id) references Position
