
/** POSITION TYPE */
create table PositionType (
	id bigint generated by default as identity,
	active boolean not null,
	businessKey varchar(255),
	custom boolean not null,
	description varchar(255),
	version timestamp,
	typeLevel integer not null,
	primary key (id)
)

/** POSITION */
create table Position (
	id bigint generated by default as identity,
	active boolean not null,
	businessKey varchar(255),
	custom boolean not null,
	description varchar(255),
	version timestamp,
	parentId bigint,
	orgUnit_id bigint,
	type_id bigint,
	primary key (id)
)
/** Positions can have sub positions */
alter table Position
	add constraint FK5wyab9dy4pmn9795juenm328a
	foreign key (parentId)
	references Position
/** Position has a TYPE.**/
alter table Position
	add constraint FKcrlfrt0dokyyf0hemkdgnte0
	foreign key (type_id)
	references PositionType


/**
* ORG UNIT DETAILS
*/

/** UNIT-TYPE */
create table UnitType (
	id bigint generated by default as identity,
	active boolean not null,
	businessKey varchar(255),
	custom boolean not null,
	description varchar(255),
	version timestamp,
	primary key (id)
)

/** ORG UNIT */
create table OrgUnit (
	id bigint generated by default as identity,
	active boolean not null,
	businessKey varchar(255),
	custom boolean not null,
	description varchar(255),
	version timestamp,
	parentId bigint,
	managerPosition_id bigint,
	type_id bigint,
	primary key (id)
)
/** Type of ORG UNIT */
alter table OrgUnit
	add constraint FKe99vy6yyb2ltvl1dj4l65nwud
	foreign key (type_id)
	references UnitType
/** Orgunits can have SUB ORG Units**/
alter table OrgUnit
	add constraint FKr077xhea74mslcd405sy6u4yj
	foreign key (parentId)
	references OrgUnit
/** The Position that Manages this Org UNIT */
alter table OrgUnit
	add constraint FK7rr2up9akn1b6ynbjgq8ldkt9
	foreign key (managerPosition_id)
	references Position
/** POSITION belongs to an ORG UNIT. **/
alter table Position
	add constraint FKepd1uklp3916m871iyp03cwt2
	foreign key (orgUnit_id)
	references OrgUnit

/** The Positions Mangaged by an ORG UNIT */
create table OrgUnit_Position (
	OrgUnitEntity_id bigint not null,
	positions_id bigint not null,
	primary key (OrgUnitEntity_id, positions_id)
)
alter table OrgUnit_Position
	add constraint UK_qugyq06u8k4hpxfeapg7eieqt unique (positions_id)
alter table OrgUnit_Position
	add constraint FKdnwt1fpxnrkush8wiqvurf68g
	foreign key (positions_id)
	references Position
alter table OrgUnit_Position
	add constraint FKjvok92mrukpvehk3jin3jtuas
	foreign key (OrgUnitEntity_id)
	references OrgUnit


/** The ORG UNITS Manged by a Position */
create table Position_OrgUnit (
	PositionEntity_id bigint not null,
	manageOrgUnits_id bigint not null,
	primary key (PositionEntity_id, manageOrgUnits_id)
)
alter table Position_OrgUnit
	add constraint UK_kl2f8rmeh3yi64xq0040uxita unique (manageOrgUnits_id)
alter table Position_OrgUnit
	add constraint FKinaonicsdpa0cbhgmjidnbet6
	foreign key (manageOrgUnits_id)
	references OrgUnit
alter table Position_OrgUnit
	add constraint FKi4n96c96ocjcwxea43kumol2h
	foreign key (PositionEntity_id)
	references Position


/** LOCATIONs */
create table Location (
	id bigint generated by default as identity,
	active boolean not null,
	businessKey varchar(255),
	custom boolean not null,
	description varchar(255),
	version timestamp,
	country varchar(255),
	line1 varchar(255),
	line2 varchar(255),
	postcode varchar(255),
	state varchar(255),
	suburb varchar(255),
	workStation varchar(255),
	parentId bigint,
	primary key (id)
)
/** Locations can have sub locations. */
alter table Location
	add constraint FKovqjlr2sko68ja02bo2fdxy36
	foreign key (parentId)
	references Location

/** IMAGE HOLDER */
create table Image (
	id bigint generated by default as identity,
	active boolean not null,
	businessKey varchar(255),
	custom boolean not null,
	description varchar(255),
	version timestamp,
	image varchar(255) for bit data,
	mimeType varchar(255),
	thumbNail varchar(255) for bit data,
	primary key (id)
)

/** CHANNEL (ie email, mobile etc) */
create table Channel (
	id bigint generated by default as identity,
	active boolean not null,
	businessKey varchar(255),
	custom boolean not null,
	description varchar(255),
	version timestamp,
	channelValue varchar(255),
	type varchar(255),
	primary key (id)
)

/** CONTACT (ie the Person) */
create table Contact (
	id bigint generated by default as identity,
	active boolean not null,
	businessKey varchar(255),
	custom boolean not null,
	description varchar(255),
	version timestamp,
	country varchar(255),
	line1 varchar(255),
	line2 varchar(255),
	postcode varchar(255),
	state varchar(255),
	suburb varchar(255),
	workStation varchar(255),
	companyTitle varchar(255),
	firstName varchar(255),
	lastName varchar(255),
	image_id bigint,
	location_id bigint,
	primary key (id)
)
/** Contact belongs to a location */
alter table Contact
	add constraint FKfphjtq0vofgr4dqi5um38wnkn
	foreign key (location_id)
	references Location
/** Contact can have an image (1:1) **/
alter table Contact
	add constraint FKha6v2q0p3tilc9iiru7qou3vl
	foreign key (image_id)
	references Image


/** Contacts can have multiple channels */
create table Contact_Channel (
	ContactEntity_id bigint not null,
	channels_id bigint not null,
	primary key (ContactEntity_id, channels_id)
)
alter table Contact_Channel
	add constraint UK_iwdhuay53ltyst9wx8cx6i0mf unique (channels_id)
alter table Contact_Channel
	add constraint FKco9j5y5frhg866vsxygpbjnn8
	foreign key (channels_id)
	references Channel
alter table Contact_Channel
	add constraint FKf2y729ik4qnfq1rn58h582y02
	foreign key (ContactEntity_id)
	references Contact


/** Contacts can manage multiple positions */
create table Contact_Position (
	ContactEntity_id bigint not null,
	positions_id bigint not null,
	primary key (ContactEntity_id, positions_id)
)
alter table Contact_Position
	add constraint FKej714lvq1osykkrtxp62pxvnx
	foreign key (ContactEntity_id)
	references Contact
alter table Contact_Position
	add constraint FK9kwegsvx5pca1pp20b9rskq1g
	foreign key (positions_id)
	references Position


/** Position can be managed by mulitple contacts */
create table Position_Contact (
	PositionEntity_id bigint not null,
	contacts_id bigint not null,
	primary key (PositionEntity_id, contacts_id)
)
alter table Position_Contact
	add constraint FKiit793ur4r60mo1ipdsjokdlu
	foreign key (contacts_id)
	references Contact
alter table Position_Contact
	add constraint FKeqx8cqg3gsbp95xeebuxs67mk
	foreign key (PositionEntity_id)
	references Position
